### PR TITLE
docs: add marketing playbook to docs

### PR DESCRIPTION
**Pull request by TC-MO**
remove pages covered by marketing playbok
add mmarketing playbook link to index page
rework index page

### CODE REVIEW

**Comment by TC-MO** [comment]
As discussed previously:

- removed pages covered by marketing playbook
- added a link to marketing playbook on the main section page
- left monetization page since it is not covered by marketing playbook

**Review by metalwarrior665 — APPROVED** [review]

**Comment by honzajavorek** [comment]
What's the idea behind the Marketing Playbook? It looks a lot like just another tentacle of Apify's docs, but separately in Notion. Is it managed by someone else than the docs team? If so, I assume the benefits are easy editability and fast changes, while reviews of the content aren't as important?

**Comment by metalwarrior665** [comment]
It is owned by the Marketing (Content) team, I guess it is just easier for them to have it in Notion. Not sure if there are plans to move it to docs.apify.com I don't think there is any hard blocker for that.

**Comment by TC-MO** [comment]
Marketing playbook in this form is handled by Marketing team, this was just a quick solution for outdated docs. The plan is to move this content into docs out of notion.

**Pull request merged**
