### PR TITLE
Add dynamic content scraping article

### PR DESCRIPTION
**Pull request by m-murasovs**
Moved from Help, left a brief summary in the Help article (the TL;DR section) and a link to docs.

https://app.intercom.com/a/apps/kod1r788/articles/articles/3339492/show?language=en

### CODE REVIEW

**Comment by metalwarrior665** [comment]
We need to correctly indent all the code examples because Intercom editor is super messy. Do you want me to do that?

**Review by mtrunkat — APPROVED** [review]

**Comment by m-murasovs** [comment]
@metalwarrior665 did you have a chance to check the indentations?

**Comment by metalwarrior665** [comment]
@m-murasovs Fixed the indentation. Unfortunately, Puppeteer deprecated `waitFor` which is super annoying so I had to rework the article partially and it is now more confusing. Please have a quick look at the English.

**Comment by m-murasovs** [comment]
@metalwarrior665 it looks good, thank you for the re-work!
Should we merge?

**Comment by metalwarrior665** [comment]
Yes, merging!

**Pull request merged**
