### PR TITLE
feat: Setup Smartlook [internal]

### PR DESCRIPTION
**Pull request by HonzaTuron**
Closes apify/apify-web#3489

Setup Smartlook for Docusaurus. Smartlook token is imported from Doppler.

Not sure abou lychee check though cc @TC-MO

### CODE REVIEW

**Comment by TC-MO** [comment]
We are aware of issue, part of python docs is not being built at the moment. I'm also not aware of any ETA for the fix for this. If this is urgent I think it should be okay to just force merge without lychee passing

**Comment by B4nan** [comment]
looks like this broke the build (or better say PR checks)

see https://github.com/apify/apify-docs/actions/runs/8435147064/job/23102478546?pr=896

**Comment by B4nan** [comment]
it breaks the local development as well, will add a dummy fallback to the env var, looks like that's enough at least locally

**Comment by B4nan** [comment]
next time please add me as a reviewer to such changes, this was really broken. another problem - the plugin dependency is only added to the apify-docs, but it needs to be in all the repositories (sdks, clients, cli)

**Comment by HonzaTuron** [comment]
Will do, sorry and thanks

**Pull request merged**
