### PR TITLE
Feature/artifacts per branch

### PR DESCRIPTION
**Pull request by mhamas**
Upload artifacts per branch to `s3://apify-docs/BRANCH_NAME`. These artifacts are then removed when branch is closed.

### CODE REVIEW

**Review by mtrunkat — APPROVED** [review]

**Review by m-murasovs — APPROVED** [review]

**Comment by mtrunkat** [comment]
@m-murasovs can we merge this one?

**Comment by m-murasovs** [comment]
@mhamas, I think I remember you said this one's not for merging?

**Comment by mhamas** [comment]
@m-murasovs depends. It's fine to merge but currently `web` only supports using docs from `master` and `develop` branches. In order to load docs from your custom branch, you need to add that branch name to https://github.com/apify/apify-web/blob/develop/src/server/lib/docs.js#L8 and restart your local apify-web server.

So really depends on your workflow. I'd probably suggest first to fix `apify-web` to be able to load data from any branch on S3 and then merge this.

**Comment by mhamas** [comment]
@m-murasovs I made changes to `apify-web` (https://github.com/apify/apify-web/pull/425) and I propose to merge this once that PR gets in.

**Comment by mhamas** [comment]
The PR on web has been merged and I verified it works well in prod. Hence merging this.

**Pull request merged**
