### PR TITLE
docs: fix markdown to disable an unnecessary link

### PR DESCRIPTION
**Pull request by honzajavorek**
I suppose this shouldn't be a real link.

### CODE REVIEW

**Review by B4nan — APPROVED** [review]
could be an inline code block too i guess

**Review by TC-MO — APPROVED** [review]

**Comment by TC-MO** [comment]
I'll wait with merging this until the https://github.com/apify/apify-docs/pull/897 us merged, as it fixes ~150 vale issues in academy and possibly these as well.

**Comment by TC-MO** [comment]
@B4nan could you take a look at these failing checks? Both of them are failing due to `SmartLook` but I thought that issue was already resolved on master?

**Comment by honzajavorek** [comment]
I made another PR, but the checks are failing with the same error: https://github.com/apify/apify-docs/pull/907

**Pull request closed without merging**
