### PR TITLE
concepts -> fingerprinting + geolocation

### PR DESCRIPTION
**Pull request by mstephen19**
Migrating two Notion articles over to the **concepts** section of the academy.

### CODE REVIEW

**Comment by mstephen19** [comment]
These are migrated from Notion. Just restructured them, added more information, and fixed the wording/spelling of stuff

**Review by mnmkng — APPROVED** [review]

**Review by m-murasovs — CHANGES_REQUESTED** [review]
The preview isn't working: https://developers.apify.com/academy/web-scraping-for-beginners?version=academy/concepts/fingerprinting+geolocation

Could you do a test branch from master with a similar kind of name that uses `+` and multiple `/` so we can see if it's the name or something in the PR? Thanks!

**Comment by mstephen19** [comment]
@m-murasovs I made a branch called `test+branch` from master, made 0 changes, and it throws 404 https://developers.apify.com/academy/web-scraping-for-beginners?version=test+branch

**Comment by mstephen19** [comment]
moved to new branch and new PR

**Pull request closed without merging**
