### PR TITLE
Integrate the Public Actor guide in actors docs

### LINKED ISSUE #223: Mov Public actor guide to docs
Conversation here: https://apifier.slack.com/archives/CQ96RHG2U/p1618840727002600

### PR DESCRIPTION
**Pull request by m-murasovs**
Integrating the PA guide from Notion into existing docs: https://www.notion.so/apify/Public-actor-Guide-7c2ef51d4c9846afa33567dc516cabfa

The preview is available here: https://docs.apify.com/actors?version=public-actor-guide

UPDATES:
- The "Actors" landing page now features some basics on building public actors and the Inspiration section: https://docs.apify.com/actors?version=public-actor-guide
- The Promotion and SEO content was added to the existing `Publishing` and `SEO` pages and SEO page renamed "SEO and promotion": https://docs.apify.com/actors/publishing/seo-and-promotion?version=public-actor-guide
- The "Development" page now contains the "Before you begin" and "Essential materials" sections that lead to public wiki pages
- Added the "Testing and maintenance" article: https://docs.apify.com/actors/development/testing-and-maintenance?version=public-actor-guide

closes #223

### CODE REVIEW

**Comment by zpelechova** [comment]
Choose just one critical thing :)
image

**Comment by novotnyo** [comment]
One link leads to our [Notion page](https://www.notion.so/apify/Public-actor-Guide-7c2ef51d4c9846afa33567dc516cabfa#e53d4d0489964a448a0405fb172cda14). 
image

This is nothing to avoid. Better would be to change Avoid to Good and Good to Better
image

**Review by zpelechova — APPROVED** [review]
Testing art:
We are saying in one sentence that testing actor is only for more complex usecases and they should primarily use Monitorning, and next is step by step guide for Testing actor. Should we provide some info for monitoring as well? 
image

2. Mabye :see bellow? I dont know where the link is going
image

**Comment by m-murasovs** [comment]
@zpelechova we already have a lot of content for monitoring, so I don't want to add anything else here. Maybe a couple more links will do the trick?

**Pull request merged**
