### PR TITLE
docs: rewrite SEO and promotion document

### PR DESCRIPTION
**Pull request by TC-MO**
new structure
added details & summary tags for examples
added admonitions
rewrites for clarity & conciseness

### CODE REVIEW

**Review by metalwarrior665 — CHANGES_REQUESTED** [review]
Thanks. We have now pretty [sophisticated marketing playbook](https://apify.notion.site/3fdc9fd4c8164649a2024c9ca7a2d0da?v=6d262c0b026d49bfa45771cd71f8c9ab) so I would link it as the top section and keep the rest as short as possible.

**Comment by TC-MO** [comment]
I don't know why I assumed that it was internal document, not viewable outside of org (and we knows what happens when one assumes something...) Maybe instead of keeping this whole section we could make it so that when you click on it in the sidebar it takes you to the marketing playbook?

**Comment by metalwarrior665** [comment]
That sounds good if you are able to do that :)

**Comment by TC-MO** [comment]
So you can checkout the results of adding marketing playbook [here](https://github.com/apify/apify-docs/pull/1341) PR's that are related to this will be closed off, with the exception of monetization guide

**Pull request closed without merging**
