### PR TITLE
feat: Update set up for Milvus database and add link to RAG notebook.

### PR DESCRIPTION
**Pull request by jirispilka**
I was asked to update the database set up based on [Mivus article](https://milvus.io/docs/apify_milvus_rag.md#Set-up-MilvusZilliz-URI-token-and-collection-name)
I also added a notebook for complete RAG

### CODE REVIEW

**Comment by jirispilka** [comment]
This issue is reported by Typos Check:
```
error: `hiddent` should be `hidden`
  --> ./sources/platform/storage/dataset.md:287:58
    |
287 | The following example demonstrates a dataset record with hiddent fields, including HTTP response and error details.
```
I would fix it but I don't want to create a conflict change

**Comment by TC-MO** [comment]
> This issue is reported by Typos Check:
> 
> ```
> error: `hiddent` should be `hidden`
>   --> ./sources/platform/storage/dataset.md:287:58
>     |
> 287 | The following example demonstrates a dataset record with hiddent fields, including HTTP response and error details.
> ```
> 
> I would fix it but I don't want to create a conflict change

That is weird, I don't see this typo anywhere?

**Review by TC-MO — COMMENTED** [review]
all checks are green

**Comment by jirispilka** [comment]
> > This issue is reported by Typos Check:
> > ```
> > error: `hiddent` should be `hidden`
> >   --> ./sources/platform/storage/dataset.md:287:58
> >     |
> > 287 | The following example demonstrates a dataset record with hiddent fields, including HTTP response and error details.
> > ```

> > I would fix it but I don't want to create a conflict change
> 
> That is weird, I don't see this typo anywhere?

It was there before. Maybe it got fixed in the meantime :)

**Pull request merged**
