### PR TITLE
style: use consistent code example language markers

### PR DESCRIPTION
**Pull request by honzajavorek**
Some examples were marked as `js`, some as `javascript`, some as `ts`, some as `typescript`. I chose the verbose variant, but in fact have no strong opinion, just wanted it to be consistent.

### CODE REVIEW

**Comment by B4nan** [comment]
We use the short variants everywhere (at least I do), imo the long ones are mostly from the past.

**Comment by TC-MO** [comment]
I have no opinion as long as syntax highlighting works correctly, but consistency is always welcome.

**Comment by honzajavorek** [comment]
Eslint punishing me for touching old stuff 😅

**Comment by TC-MO** [comment]
apparently if we want to go for the shortest one we could change all `python` to `py`, but not sure if there is a point to it.

**Comment by honzajavorek** [comment]
@TC-MO I'm okay with it! I added [a663e40](https://github.com/apify/apify-docs/pull/1027/commits/a663e4064dd4b141793a0a2174aad829d0d814fe) 🐍 

Apart from one randomly timeouting link and ESlint I think all should be fine. I don't feel like I should fix lint errors in code as part of this PR just because I've touched the files, I'd like to keep the PR focused only on changing the code block markers.

Is it okay to merge like this?

**Comment by TC-MO** [comment]
From lychee standpoint I'm ok, this link has been timing out multiple times on multiple pages. Not sure about ESlint maybe @B4nan can weigh in?

**Review by TC-MO — APPROVED** [review]
LGTM

**Comment by honzajavorek** [comment]
I'll do it. Found `npm run lint:code:fix`, that already did half of the job.

**Comment by honzajavorek** [comment]
Okay, so I did my best, but I couldn't fix it all. I'm not proficient in TypeScript, React, or the JavaScript Apify SDK to fix stuff like "Unexpected any. Specify a different type" or "React Hook "Actor.useState" cannot be called at the top level. React Hooks must be called in a React function component or a custom React Hook function".

I'll let the build to finish, see if only these errors are left, and then I'll merge this PR.

**Comment by honzajavorek** [comment]
All green except those three linter errors. Merging!

**Comment by honzajavorek** [comment]
Apparently it fails on `master` too 🙀 I thought it only lints changes! Filed https://github.com/apify/apify-docs/issues/1068

**Pull request merged**
